---
# Port forwarding 
- name: Redirect port 443 to 8443 with Rich Rule
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 forward-port port=8080 protocol=tcp to-port=8084
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
  tags: firewall



# Ingress Rule
- name: Add foodmgt internal port to firewall rule
  ansible.posix.firewalld:
    zone: public
    port: 8086/tcp
    permanent: yes
    immediate: yes
    state: enabled
  tags: foodmgt-fw

# Ingress Rule
- name: Add gkstatsapi internal port to firewall rule
  ansible.posix.firewalld:
    zone: public
    port: 5001/tcp
    permanent: yes
    immediate: yes
    state: enabled
  tags: firewall

# Ingress Rule
- name: Add gkstatsfrontend external port to firewall rule
  ansible.posix.firewalld:
    zone: public
    port: 8082/tcp
    permanent: yes
    immediate: yes
    state: enabled
  tags: firewall

# Ingress Rule
- name: Add foodmgt external port to firewall rule
  ansible.posix.firewalld:
    zone: public
    port: 8087/tcp
    permanent: yes
    immediate: yes
    state: enabled
  tags: firewall

# Ingress Rule for prod
- name: Add foodmgt external port to firewall rule
  ansible.posix.firewalld:
    zone: public
    port: 8443/tcp
    permanent: yes
    immediate: yes
    state: enabled
  tags: firewall

# Ingress Rule for prod
- name: Add foodmgt external port to firewall rule
  ansible.posix.firewalld:
    zone: public
    port: 443/tcp
    permanent: yes
    immediate: yes
    state: enabled
  tags: firewall




#- ansible.posix.firewalld:
#    source: 192.0.2.0/24
#    zone: internal
#    state: enabled