---
- name: 'update apt packages.'
  become: true
  yum:
    update_cache: yes

- name: Upgrade all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: 'Remove dependencies that are no longer required'
  become: true
  yum:
    autoremove: yes

